replicaCount: 2

image:
  repository: jksolbakken/helloworld
  pullPolicy: Always
  tag: "1.20250413171118"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false

securityContext:
  capabilities:
    drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

container:
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 16Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http

